### ISSUE TITLE
Simple and fast geodesics for spheres?

### ISSUE THREAD

**Issue by milankl** [JuliaGeo/SphericalGeodesics.jl#1]
Hi Andy! Thank for your various packages around geodesics. @treigerm and I are looking for a way to calculate geodesics on the sphere (Earth, but radius should be a parameter) for [SpeedyWeather.jl](https://github.com/SpeedyWeather/SpeedyWeather.jl) arising from this issue 

https://github.com/SpeedyWeather/RainMaker.jl/pull/15#discussion_r1795130811

We see that you've authored several packages on this but they do seem to take various approaches to this. Ideally, we are looking for something like `geodesic_distance((lond1, latd1), (lond2, latd2); radius)` that is rather fast and robust than accurate. Ideally also not a package that has many dependencies -- I would even write our own version if that's possible in a some not too many lines of code but it does seem that the algorithms you wrote for this are a bit more complicated. I don't mind a small dependency either and maybe that's also in other people's interest. We don't need geodesics for anything else than the sphere.

What's your plan with this package vs the others? If you would want us to depend on one of them which one would you recommend? Many thanks!

**Comment by asinghvi17** [comment]
As I understand this package is primarily for ellipsoidal geodesics (maybe we should rename it in that light :D) but GeometryOps plans to offer at some point in the near future a choice between planar, spherical and geodesic computations.  The algorithms here are all translations of Karney's algorithms (from the GeographicLib C package, also used in Proj), which are made for ellipsoids.

(GeometryOps does have quite a few dependencies, although we could potentially offer a `SphericalGeometryCore` package separately if there's enough interest.

Spheres allow you to drastically simplify the math.  If you just want spherical distance, then it's probably easier to compute it using either the haversine formula or by going to Cartesian (x, y, z) coordinates on the sphere, and using dot and cross products.  Note that using `cosd` and `sind` is remarkably more accurate than using `deg2rad` here.  The Wikipedia formulae you'll find usually use the physical standard for spherical coordinates, where phi is the colatitude (90-lat) not the latitude.

**Comment by anowacki** [comment]
Hi @milankl.  If you are having problems with Vincenty and antipodal points and need to work on ellipsoids, I agree you probably don't want to write up an appropriate algorithm.  But implementing the Haversine algorithm is very easy and so you may want to just copy this and vendor it yourself.

This empty package will be the future home of a merged Geodesics.jl and GeographicLib.jl.  The current plan is that the user can choose the algorithm to prioritise speed or accuracy (and choose the precision of data types).  E.g., `ellipsoid = Sphere(1_000.0); surface_distance(Haversine(ellipsoid), lon1, lat1, lon2, lat2)`.  That will then

**Comment by asinghvi17** [comment]
Ah damn, we should really unify our approaches at some point @anowacki :D.  I'm planning for a very similar API in GeometryOps, we should probably use the same types as well.  Will open another issue to discuss this.

**Comment by milankl** [comment]
Okay Haversine it is then, could you point to where you've coded that up in any of these packages if you're happy for me to copy that over?

**Comment by anowacki** [comment]
Also, This package will probably have no other dependents if that is attractive.

**Comment by anowacki** [comment]
> could you point to where you've coded that up in any of these packages if you're happy for me to copy that over?

Very happy.  Have a look at https://github.com/anowacki/SphericalGeom.jl.  It's under the usual MIT licence so you're more than welcome to use it subject to those terms.

**Comment by anowacki** [comment]
> Ah damn, we should really unify our approaches at some point

I'd be happy to do that.  My aim is for a low- or zero-dependency geodesic package which I need to deal with things on the Earth and other planets, and apparently other people have similar needs, but I don't mind in particular where this stuff lives.  But I think I will pursue putting these three algorithms in here for now.

**Comment by anowacki** [comment]
Closing this since the Haversine calculations are already done and will be pushed up alongisde the other methods when done.
